services:
  api-gateway:
    build:
      context: .
    container_name: api-gateway
    ports:
      - "3011:3011"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3011
      EVENT_SERVICE_URL: http://event-service:3021

    networks:
      - user-interface
      - api-gateway

networks:
  user-interface:
    external: true
  api-gateway:
    external: true