services:
  api-gateway:
    build:
      context: .
    container_name: api-gateway
    ports:
      - "3011:3011"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3011