services:
  explorer-ui:
    build: .
    container_name: explorer-ui
    ports:
      - "3001:80"
    environment:
      - PUBLIC_API_BASE_URL=http://localhost:3011
      - NODE_ENV=production
      - PORT=3001
    networks:
      - user-interface
    restart: unless-stopped

networks:
  user-interface:
    external: true