services:
  geo-db:
    image: postgres:16
    container_name: geo-db
    environment:
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo123
      POSTGRES_DB: geo_db
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
