services:
  admin-ui:
    build: .
    container_name: admin-ui
    ports:
      - "3002:80"
    environment:
      - PUBLIC_API_BASE_URL=http://localhost:3011
      - NODE_ENV=production
      - PORT=3002
    networks:
      - user-interface
    restart: unless-stopped

networks:
  user-interface:
    external: true